# Generated by Django 5.2.8 on 2025-11-20 01:48

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='active', max_length=20)),
                ('onboarding_location', models.CharField(blank=True, max_length=255, null=True)),
                ('onboarding_time', models.DateTimeField(auto_now_add=True)),
                ('destination_location', models.CharField(max_length=255)),
                ('destination_time', models.DateTimeField(auto_now=True)),
                ('cumulative_distance', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cumulative_journey_duration', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('route_used', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('last_login_method', models.CharField(choices=[('email_password', 'Email/Password'), ('google_oauth', 'Google OAuth')], default='email_password', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journeys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='journeys_user_id_5031be_idx'), models.Index(fields=['status'], name='journeys_status_137fed_idx'), models.Index(fields=['created_at'], name='journeys_created_d28fa2_idx')],
            },
        ),
    ]
