services:
  moti_backend:
    mem_limit: 2g
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn moti_backend.wsgi:application --bind 0.0.0.0:8000 --workers 1 --timeout 120
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: moti_backend.settings
      PORT: 8000
      PG_HOST: db
      PG_PORT: 5432
      PG_USER: motiuser
      PG_PASSWORD: motipass
      PG_DB: motidb
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - moti_backend_network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: motiuser
      POSTGRES_PASSWORD: motipass
      POSTGRES_DB: motidb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U motiuser -d motidb"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - moti_backend_network

volumes:
  pgdata:

networks:
  moti_backend_network:
    driver: bridge
